sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexoPrj # build master branch only
script:
  - hexo generate # generate static files
after_success:                # script 阶段成功时执行，构建失败不会执行，其他同上
  - git config --local user.name "fh32393900"
  - git config --local user.email "332393900@qq.com"
  - sed -i'' "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: hexoPrj
  local-dir: public