sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexoPrj # build master branch only
script:
  - hexo clean
  - hexo g
  - hexo algolia
  - hexo deploy # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: hexoPrj
  local-dir: public